"""devgear のライブラリモジュール。"""

from devgear.lib.agent_compress import compress_to_catalog
from devgear.lib.core_utils import (
    IS_LINUX,
    IS_MACOS,
    IS_WINDOWS,
    append_file,
    count_in_file,
    ensure_dir,
    find_files,
    get_claude_dir,
    get_date_string,
    get_datetime_string,
    get_git_repo_name,
    get_home_dir,
    get_learned_skills_dir,
    get_legacy_sessions_dir,
    get_project_name,
    get_session_id_short,
    get_session_search_dirs,
    get_sessions_dir,
    get_temp_dir,
    get_time_string,
    grep_file,
    read_file,
    replace_in_file,
    run_command,
    sanitize_session_id,
    write_file,
)
from devgear.lib.git_hosting import (
    GITHUB,
    GITLAB,
    VALID_GIT_HOSTING_SERVICES,
    build_git_hosting_item_url,
    detect_git_hosting_service,
    extract_git_hosting_item_details,
    get_git_hosting_cli_name,
    get_git_hosting_create_command,
    get_git_hosting_item_label,
    get_git_hosting_item_short_label,
    get_git_hosting_review_command,
    get_git_hosting_service_label,
    normalize_git_hosting_service,
)
from devgear.lib.hook_flags import (
    VALID_PROFILES,
    get_hook_profile,
    is_hook_enabled,
    normalize_id,
    parse_profiles,
)
from devgear.lib.project_detect import (
    FRAMEWORK_RULES,
    LANGUAGE_RULES,
    FrameworkRule,
    LanguageRule,
    ProjectInfo,
    detect_frameworks,
    detect_languages,
    detect_project,
    get_build_command,
    get_test_command,
)
from devgear.lib.resolve_devgear_root import resolve_devgear_root
from devgear.lib.shell_split import split_shell_segments

__all__ = [
    # agent_compress 関連
    "compress_to_catalog",
    # hook_flags 関連
    "VALID_PROFILES",
    "get_hook_profile",
    "is_hook_enabled",
    "normalize_id",
    "parse_profiles",
    # git_hosting 関連
    "GITHUB",
    "GITLAB",
    "VALID_GIT_HOSTING_SERVICES",
    "build_git_hosting_item_url",
    "detect_git_hosting_service",
    "extract_git_hosting_item_details",
    "get_git_hosting_cli_name",
    "get_git_hosting_create_command",
    "get_git_hosting_item_label",
    "get_git_hosting_item_short_label",
    "get_git_hosting_review_command",
    "get_git_hosting_service_label",
    "normalize_git_hosting_service",
    # project_detect 関連
    "FRAMEWORK_RULES",
    "LANGUAGE_RULES",
    "FrameworkRule",
    "LanguageRule",
    "ProjectInfo",
    "detect_frameworks",
    "detect_languages",
    "detect_project",
    "get_build_command",
    "get_test_command",
    # resolve_devgear_root 関連
    "resolve_devgear_root",
    # shell_split 関連
    "split_shell_segments",
    # utils 関連
    "IS_LINUX",
    "IS_MACOS",
    "IS_WINDOWS",
    "append_file",
    "count_in_file",
    "ensure_dir",
    "find_files",
    "get_claude_dir",
    "get_date_string",
    "get_datetime_string",
    "get_git_repo_name",
    "get_home_dir",
    "get_learned_skills_dir",
    "get_legacy_sessions_dir",
    "get_project_name",
    "get_session_id_short",
    "get_session_search_dirs",
    "get_sessions_dir",
    "get_temp_dir",
    "get_time_string",
    "grep_file",
    "read_file",
    "replace_in_file",
    "run_command",
    "sanitize_session_id",
    "write_file",
]
